
vscode:
  extensions:
    - 42Crunch.vscode-openapi
 
tasks:
  - name: Initialize & Configure AWS
    env:
      AWS_CLI_AUTO_PROMPT: on-partial  
    command: bash $GITPOD_REPO_ROOT/configure_aws_with_gitpod.sh
